export const JOB_LOAD_REQUEST = "JOB_LOAD_REQUEST"
export const JOB_LOAD_SUCCESS = "JOB_LOAD_SUCCESS"
export const JOB_LOAD_FAIL = "JOB_LOAD_FAIL"
export const JOB_LOAD_RESET = "JOB_LOAD_RESET"

export const JOB_TYPE_LOAD_REQUEST = "JOB_TYPE_LOAD_REQUEST"
export const JOB_TYPE_LOAD_SUCCESS = "JOB_TYPE_LOAD_SUCCESS"
export const JOB_TYPE_LOAD_FAIL = "JOB_TYPE_LOAD_FAIL"
export const JOB_TYPE_LOAD_RESET = "JOB_TYPE_LOAD_RESET"

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL"
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET"

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL'
export const USER_LOGOUT_RESET = 'USER_LOGOUT_RESET'

export const USER_LOAD_REQUEST = 'USER_LOAD_REQUEST';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOAD_FAIL = 'USER_LOAD_FAIL';
export const USER_LOAD_RESET = 'USER_LOAD_RESET';

export const JOB_LOAD_SINGLE_REQUEST = "JOB_LOAD_SINGLE_REQUEST";
export const JOB_LOAD_SINGLE_SUCCESS = "JOB_LOAD_SINGLE_SUCCESS";
export const JOB_LOAD_SINGLE_FAIL = "JOB_LOAD_SINGLE_FAIL";
export const JOB_LOAD_SINGLE_RESET = "JOB_LOAD_SINGLE_RESET";

export const USER_APPLY_JOB_REQUEST = 'USER_APPLY_JOB_REQUEST';
export const USER_APPLY_JOB_SUCCESS = 'USER_APPLY_JOB_SUCCESS';
export const USER_APPLY_JOB_FAIL = 'USER_APPLY_JOB_FAIL';
export const USER_APPLY_JOB_RESET = 'USER_APPLY_JOB_RESET';

export const ALL_USERS_LOAD_REQUEST = 'ALL_USERS_LOAD_REQUEST';
export const ALL_USERS_LOAD_SUCCESS = 'ALL_USERS_LOAD_SUCCESS';
export const ALL_USERS_LOAD_FAIL = 'ALL_USERS_LOAD_FAIL';
export const ALL_USERS_LOAD_RESET = 'ALL_USERS_LOAD_RESET';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'
export const USER_SIGNUP_RESET = 'USER_SIGNUP_RESET'

export const DELETE_USER_LOAD_REQUEST = 'DELETE_USER_LOAD_REQUEST';
export const DELETE_USER_LOAD_SUCCESS = 'DELETE_USER_LOAD_SUCCESS';
export const DELETE_USER_LOAD_FAIL = 'DELETE_USER_LOAD_FAIL';
export const DELETE_USER_LOAD_RESET = 'DELETE_USER_LOAD_RESET';

export const SINGLE_USER_LOAD_REQUEST = 'SINGLE_USER_LOAD_REQUEST';
export const SINGLE_USER_LOAD_SUCCESS = 'SINGLE_USER_LOAD_SUCCESS';
export const SINGLE_USER_LOAD_FAIL = 'SINGLE_USER_LOAD_FAIL';
export const SINGLE_USER_LOAD_RESET = 'SINGLE_USER_LOAD_RESET';

export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL';
export const CREATE_JOB_RESET = 'CREATE_JOB_RESET';

export const DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';
export const DELETE_JOB_FAIL = 'DELETE_JOB_FAIL';
export const DELETE_JOB_RESET = 'DELETE_JOB_RESET';

export const CREATE_JOB_TYPE_REQUEST = 'CREATE_JOB_TYPE_REQUEST';
export const CREATE_JOB_TYPE_SUCCESS = 'CREATE_JOB_TYPE_SUCCESS';
export const CREATE_JOB_TYPE_FAIL = 'CREATE_JOB_TYPE_FAIL';
export const CREATE_JOB_TYPE_RESET = 'CREATE_JOB_TYPE_RESET';

export const DELETE_JOB_TYPE_REQUEST = 'DELETE_JOB_TYPE_REQUEST';
export const DELETE_JOB_TYPE_SUCCESS = 'DELETE_JOB_TYPE_SUCCESS';
export const DELETE_JOB_TYPE_FAIL = 'DELETE_JOB_TYPE_FAIL';
export const DELETE_JOB_TYPE_RESET = 'DELETE_JOB_TYPE_RESET';