export const JOB_LOAD_REQUEST = "JOB_LOAD_REQUEST"
export const JOB_LOAD_SUCCESS = "JOB_LOAD_SUCCESS"
export const JOB_LOAD_FAIL = "JOB_LOAD_FAIL"
export const JOB_LOAD_RESET = "JOB_LOAD_RESET"

export const JOB_TYPE_LOAD_REQUEST = "JOB_TYPE_LOAD_REQUEST"
export const JOB_TYPE_LOAD_SUCCESS = "JOB_TYPE_LOAD_SUCCESS"
export const JOB_TYPE_LOAD_FAIL = "JOB_TYPE_LOAD_FAIL"
export const JOB_TYPE_LOAD_RESET = "JOB_TYPE_LOAD_RESET"

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL"
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET"